import { Hono } from 'hono'
import { HTTPException } from 'hono/http-exception'

import { events } from './events'

// API path will be at /api/v1
export const api = new Hono().basePath('/v1')

api.route('/events', events)

api.onError((err, c) => {
  console.error(err)

  if (err instanceof HTTPException) {
    if (err.cause) {
      console.error(err.cause)
    }

    // Return the error response generated by HTTPException
    return c.json(
      {
        error: {
          status: err.status,
          message: err.message,
        },
      },
      err.status,
    )
  }

  // For any other unexpected errors, log and return a generic 500 response
  return c.text('Internal Server Error', 500)
})
